name: ci pipeline
on:
  pull_request:
    branches:
      - "**"

jobs:
  Continuous-integration:
    name: Performs linting, formatting on the application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3
      - name: Install Dependency
        run: npm install
      - name: Run build
        run: npm run build
